'use strict';
const $=id=>document.getElementById(id);
let token='', images=[], busy=false, approved=false;
const reportKeys=['description','conclusion','limitations'];
function message(text){$('message').textContent=text;}
function invalidate(){approved=false;$('review').checked=false;$('report-state').textContent='Черновик';}
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-Local-Token':token}:{},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok)throw Error(result.error||'Ошибка запроса');return result;}
function render(){const gallery=$('gallery');gallery.replaceChildren();images.forEach((item,i)=>{const tile=document.createElement('div');tile.className='tile';const img=document.createElement('img');img.src='data:image/png;base64,'+item.image;img.alt='Снимок УЗИ '+(i+1);const caption=document.createElement('span');caption.textContent='Снимок '+(i+1)+(item.metadata.frames>1?' · первый из '+item.metadata.frames+' кадров':'');const button=document.createElement('button');button.textContent='Удалить';button.disabled=busy;button.onclick=()=>{images.splice(i,1);invalidate();render();};tile.append(img,caption,button);gallery.append(tile);});$('count').textContent=images.length+' / 6';}
async function upload(files){if(busy)return;setBusy(true);message('Обработка снимков…');try{for(const file of files){if(images.length>=6){message('Допускается не более 6 снимков.');break;}if(file.size>20*1024*1024){message('Файл превышает 20 МБ.');continue;}try{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await api('/api/convert',{image:btoa(binary)});images.push(result);$('privacy').checked=false;invalidate();}catch(e){message(e.message);}}render();$('status').textContent='Исследование загружено';if(images.length)message('Проверьте наличие персональных данных на изображениях.');}finally{setBusy(false);$('upload').value='';}}
function setBusy(value){busy=value;document.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=value);$('upload').disabled=value;render();}
async function models(){try{const result=await api('/api/models');$('model').replaceChildren();for(const name of result.models){const option=document.createElement('option');option.value=name;option.textContent=name;$('model').append(option);}if(!result.models.length){const option=document.createElement('option');option.value='';option.textContent='Модель не подключена';$('model').append(option);}$('model-state').textContent=result.error||'Выберите модель с поддержкой изображений. Общие модели не валидированы для УЗИ.';}catch(e){message(e.message);}}
$('upload').onchange=e=>upload(e.target.files);
$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files);};
$('refresh').onclick=models;
$('analyze').onclick=async()=>{if(!images.length)return message('Добавьте хотя бы один снимок.');if(!$('privacy').checked)return message('Проверьте снимки и подтвердите отсутствие персональных данных.');if(!$('model').value)return message('Сначала подключите локальную модель Ollama.');if(!$('age').checkValidity())return message('Проверьте возраст: от 0 до 120 лет.');setBusy(true);invalidate();message('Модель анализирует снимки. Это может занять несколько минут…');try{const data={images:images.map(x=>x.image),privacy_confirmed:true,model:$('model').value};for(const key of ['organ','age','indication','measurements','observations'])data[key]=$(key).value;const result=await api('/api/analyze',data);reportKeys.forEach(k=>$(k).value=result[k]);$('status').textContent='Черновик готов';message('Черновик сформирован. Проверьте каждый раздел по исходным изображениям.');}catch(e){message(e.message);}finally{setBusy(false);}};
$('manual').onclick=()=>{invalidate();$('description').value=[$('observations').value,$('measurements').value].filter(Boolean).join('\n')||'Описание не заполнено врачом.';$('conclusion').value='';$('limitations').value='Составлено по введенным данным врача. ИИ-анализ изображений не выполнялся.';message('Данные врача перенесены. Заполните заключение.');};
document.querySelectorAll('textarea,input:not([type=file]),select').forEach(el=>{if(el.id!=='review')el.addEventListener('input',invalidate);});
$('approve').onclick=()=>{if(!reportKeys.slice(0,2).every(k=>$(k).value.trim()))return message('Заполните описание и заключение.');if(!$('doctor').value.trim()||!$('review').checked)return message('Укажите врача и подтвердите проверку протокола.');approved=true;$('report-state').textContent='Проверено врачом';message('Протокол подтвержден. Его можно сохранить или распечатать.');};
function report(){return {application:'SonoCopilot — исследовательская версия',created_at:new Date().toISOString(),status:approved?'Проверено врачом':'Черновик, не подтвержден',organ:$('organ').value,age:$('age').value,indication:$('indication').value,measurements:$('measurements').value,doctor:$('doctor').value,...Object.fromEntries(reportKeys.map(k=>[k,$(k).value]))};}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(report(),null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='sonocopilot-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
$('print').onclick=()=>{const r=report();const popup=window.open('','_blank');if(!popup)return message('Разрешите окно печати в браузере.');const doc=popup.document;doc.title='Протокол УЗИ';const title=doc.createElement('h1');title.textContent='Протокол УЗИ · '+r.organ;doc.body.append(title);for(const [label,value] of [['Статус',r.status],['Дата',new Date(r.created_at).toLocaleString('ru-RU')],['Возраст',r.age||'Не указан'],['Показания',r.indication],['Измерения',r.measurements],['Описание',r.description],['Заключение',r.conclusion],['Ограничения',r.limitations],['Врач',r.doctor]]){const h=doc.createElement('h3');h.textContent=label;const p=doc.createElement('p');p.textContent=value;p.style.whiteSpace='pre-wrap';doc.body.append(h,p);}popup.print();};
$('reset').onclick=()=>{if(!confirm('Очистить текущее исследование? Несохраненные данные будут удалены.'))return;images=[];document.querySelectorAll('input,textarea').forEach(el=>{el.value='';if(el.type==='checkbox')el.checked=false;});invalidate();render();$('status').textContent='Новое исследование';message('');};
(async()=>{try{token=(await api('/api/config')).token;await models();}catch(e){message('Не удалось подключиться к серверу: '+e.message);}})();

